# Site settings
title: Jonathan Senecal
author: Jonathan Senecal
email: contact@jonathansenecal.com
description:
  en: Jonathan Senecal - Personal Page
  fr: Jonathan Senecal - Page Personnelle
keywords: ["cv", "resume", "networking", "réseau", "project manager", "gestion de projets", "curriculum vitae", "work", "travail",
          "experience", "guru"]
index: index.html
feed: /feed.xml
baseurl: "/" # the subpath of your site, e.g. /blog
collections:
  - sections
url: "https://www.jonathansenecal.com" # the base hostname & protocol for your site
twitter_username: infinityzxx
github_username:  jsenecal

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-polyglot

# i18n specific config
languages: ["en", "fr"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true