# Site settings
title:
  en: Jonathan Senecal - Resume
  fr: Jonathan Senecal - Page perso
author:
  name: Jonathan Senecal
  email: contact@jonathansenecal.com
  phone: 514.710.0100
  dob:
    en: September 6, 1985
    fr: 6 Septembre 1985
  address:
    en: 7787 de Bordeaux street, Montreal (Quebec), Canada
    fr: 7787 rue de Bordeaux, Montréal (Quebec), Canada
  nationality:
    en: Canadian
    fr: Canadienne
description:
  en: Jonathan Senecal - Personal Page
  fr: Jonathan Senecal - Page Personnelle
keywords: ["cv", "resume", "networking", "réseau", "project manager", "gestion de projets", "curriculum vitae", "work", "travail",
          "experience", "guru"]
index:
  en: index.en.html
  fr: index.fr.html
feed: /feed.xml
baseurl: "/"
collections:
  - sections
url: "https://www.jonathansenecal.com"

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-polyglot

# i18n specific config
languages: ["en", "fr"]
default_lang: "en"
exclude_from_localization: ["images", "css"]
parallel_localization: true

exclude: [.idea,]